title:
  Example Blog Post
filename:
  example-blog-post
description:
  This is an example of a yaml metadata doc for the dblog package
pubdate:
  2023-10-31
# if update not specified, it'll just be pubdate
updatedate:
  2023-11-01
tags:
- math
- history
- articles
- code
# thumbnail is completely optional
thumbnail:
  src: path/to/some/pic.jpg
  alt: description of image
  title: witty remark about image
