Title:
  Example Blog Post
FileName:
  example-blog-post
Description:
  This is an example of a yaml metadata doc for the dblog package
PubDate:
  2023-10-31
# if update not specified, it'll just be pubdate
UpdateDate:
  2023-11-01
Tags:
  - Name: math
  - Name: history
  - Name: articles
  - Name: code
# thumbnail is completely optional
Thumbnail:
  Src: path/to/some/pic.jpg
  Alt: description of image
  Title: witty remark about image
